project:
  type: book

book:
  title: "Quarto Presentation"
  author: "Guerzoniansu"
  date: "01/06/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



